// Code generated by hertz generator.

package course

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createcourseplanMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatecourseplanMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletecourseplanMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getcourseprogressMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _resetcourseprogressMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatecourseprogressMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _planMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getcourseplanMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getcourseplanidsMw() []app.HandlerFunc {
	// your code...
	return nil
}
